In [1]:
import numpy as np 
import pandas as pd

In [12]:
# merge two dataframes 

employees =pd.DataFrame({
    "employee_id":[1,2,3,4,5],
    "NAME":["CHETAN ", "HARI","RAM","ROHAN","RICHA"],
    "DEPARTMENT":["HR","IT","HR","IT","FINANCE"]
    
})
SALARIES = pd.DataFrame({
    "employee_id":[1,2,3,6,7],
    "salary":[6000,5000,460000,30000,20000],
    "bonus":[2000,3000,2000,1000,6000]
})

In [3]:
employees

   employee_id     NAME DEPARTMENT
0            1  CHETAN          HR
1            2     HARI         IT
2            3      RAM         HR
3            4    ROHAN         IT
4            5    RICHA    FINANCE

In [13]:
SALARIES

   employee_id  salary  bonus
0            1    6000   2000
1            2    5000   3000
2            3  460000   2000
3            6   30000   1000
4            7   20000   6000

In [14]:
pd.merge(employees,SALARIES,on="employee_id",how="inner")

   employee_id     NAME DEPARTMENT  salary  bonus
0            1  CHETAN          HR    6000   2000
1            2     HARI         IT    5000   3000
2            3      RAM         HR  460000   2000

In [15]:
pd.merge(employees,SALARIES,on="employee_id",how="left")

   employee_id     NAME DEPARTMENT    salary   bonus
0            1  CHETAN          HR    6000.0  2000.0
1            2     HARI         IT    5000.0  3000.0
2            3      RAM         HR  460000.0  2000.0
3            4    ROHAN         IT       NaN     NaN
4            5    RICHA    FINANCE       NaN     NaN

In [16]:
pd.merge(employees,SALARIES,on="employee_id",how="right")

   employee_id     NAME DEPARTMENT  salary  bonus
0            1  CHETAN          HR    6000   2000
1            2     HARI         IT    5000   3000
2            3      RAM         HR  460000   2000
3            6      NaN        NaN   30000   1000
4            7      NaN        NaN   20000   6000

In [17]:
pd.merge(employees,SALARIES,on="employee_id",how="outer")

   employee_id     NAME DEPARTMENT    salary   bonus
0            1  CHETAN          HR    6000.0  2000.0
1            2     HARI         IT    5000.0  3000.0
2            3      RAM         HR  460000.0  2000.0
3            4    ROHAN         IT       NaN     NaN
4            5    RICHA    FINANCE       NaN     NaN
5            6      NaN        NaN   30000.0  1000.0
6            7      NaN        NaN   20000.0  6000.0

In [18]:
# concatination two dataframes

In [19]:
df1 =pd.DataFrame({
    "A":["A0","A1","A2"],
    "B":["B0","B1","B2"],
    "C":["C0","C1","C2"]
    
})
df2 = pd.DataFrame({
    "A":["A3","A4","A5"],
    "B":["B3","B4","B5"],
    "C":["C3","C4","C5"]
})

In [20]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [21]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [22]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [23]:
pd.concat([df1,df2],axis=0)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [24]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [25]:
# joining operation

In [27]:
df1 =pd.DataFrame({
    "name":["heri","linda","charlie"]
},index=[1,2,3])

df2 =pd.DataFrame({
    "score":[85,78,98]
},index=[2,3,4])

In [28]:
df1

      name
1     heri
2    linda
3  charlie

In [29]:
df2

   score
2     85
3     78
4     98

In [32]:
df1.join(df2)

      name  score
1     heri    NaN
2    linda   85.0
3  charlie   78.0

In [33]:
df1.join(df2,how="outer")

      name  score
1     heri    NaN
2    linda   85.0
3  charlie   78.0
4      NaN   98.0