In [1]:
import numpy as np 

import pandas as pd

In [2]:
data = {
    "A":[1,2,3,np.nan ,5],
    "B":[1,np.nan,3,4,5],
    "C":[1,2,3,np.nan,np.nan],
    "D":[1,2,np.nan,np.nan,np.nan]
}
d1 = pd.DataFrame(data)
d1

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  NaN  2.0  2.0
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  5.0  5.0  NaN  NaN

In [3]:
# SEARCH NULL VALUES

d1.isna()

       A      B      C      D
0  False  False  False  False
1  False   True  False  False
2  False  False  False   True
3   True  False   True   True
4  False  False   True   True

In [5]:
# SUM  OF NULL VALUES

d1.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [5]:
# SEARCH AND CHECK NULL VALUES 
d1.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [4]:
d1

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  NaN  2.0  2.0
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  5.0  5.0  NaN  NaN

In [8]:
# remove the null values
d1.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  2.0

In [10]:
d1

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  2.0
2  3.0  3  3.0  NaN
3  NaN  4  NaN  NaN
4  5.0  5  NaN  NaN

In [12]:
d1.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  2.0

In [14]:
d1

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  NaN  2.0  2.0
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  5.0  5.0  NaN  NaN

In [18]:
d1.dropna(thresh=4)

     A    B    C    D
0  1.0  1.0  1.0  1.0

In [19]:
d1

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  NaN  2.0  2.0
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  5.0  5.0  NaN  NaN

In [21]:
# fill null valuesn
d1.fillna(0)

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  0.0  2.0  2.0
2  3.0  3.0  3.0  0.0
3  0.0  4.0  0.0  0.0
4  5.0  5.0  0.0  0.0

In [22]:
# fill null values with some different values 
values = {"A":200,"B":250,"C":100,"D":200}
d1.fillna(value=values)

       A      B      C      D
0    1.0    1.0    1.0    1.0
1    2.0  250.0    2.0    2.0
2    3.0    3.0    3.0  200.0
3  200.0    4.0  100.0  200.0
4    5.0    5.0  100.0  200.0

In [23]:
d1

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  NaN  2.0  2.0
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  5.0  5.0  NaN  NaN

In [24]:
d1.fillna(d1.mean())

      A     B    C    D
0  1.00  1.00  1.0  1.0
1  2.00  3.25  2.0  2.0
2  3.00  3.00  3.0  1.5
3  2.75  4.00  2.0  1.5
4  5.00  5.00  2.0  1.5