In [1]:
# CREATING A DATAFRAMES

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data ={
    'NAME': ['JOHN','MOTU','PATLU','HARI'],
    'AGE':[34,30,28,25],
    'CITY':['NEW YORK','UK','PARIES','BHOPAL'],
    'SALARY':[65000,70000,50000,20000]

}
d1 = pd.DataFrame(data)
d1

    NAME  AGE      CITY  SALARY
0   JOHN   34  NEW YORK   65000
1   MOTU   30        UK   70000
2  PATLU   28    PARIES   50000
3   HARI   25    BHOPAL   20000

In [3]:
# create  a dataframes in list

In [5]:
data_list = [
    ["Ram ",34, "bhopal",5000],
    ["chetan",21 ,"indore",10000],
    ["hari",22,"delhi",16000]
]
d2= pd.DataFrame(data_list)
d2

        0   1       2      3
0    Ram   34  bhopal   5000
1  chetan  21  indore  10000
2    hari  22   delhi  16000

In [6]:
column = ["NAME","AGE","CITY","SALARY"]
d2=pd.DataFrame(data_list,columns=column)
d2

     NAME  AGE    CITY  SALARY
0    Ram    34  bhopal    5000
1  chetan   21  indore   10000
2    hari   22   delhi   16000

In [7]:
# selecting or indexing the dataframe

In [8]:
d2["NAME"]

0      Ram
1    chetan
2      hari
Name: NAME, dtype: object

In [10]:
# SELCET MULTIPLE COLUMNS IN DATAFRAME

In [16]:
d2 [["NAME","AGE","CITY","SALARY"]]

     NAME  AGE    CITY  SALARY
0    Ram    34  bhopal    5000
1  chetan   21  indore   10000
2    hari   22   delhi   16000

In [17]:
# CREATING A NEW COLUMN IN DATAFRAME

In [20]:
d2["designation"] = ["doctor","eng","teacher"]
d2

     NAME  AGE    CITY  SALARY designation
0    Ram    34  bhopal    5000      doctor
1  chetan   21  indore   10000         eng
2    hari   22   delhi   16000     teacher

In [21]:
d2

     NAME  AGE    CITY  SALARY designation
0    Ram    34  bhopal    5000      doctor
1  chetan   21  indore   10000         eng
2    hari   22   delhi   16000     teacher

In [23]:
d2

     NAME  AGE    CITY  SALARY designation
0    Ram    34  bhopal    5000      doctor
1  chetan   21  indore   10000         eng
2    hari   22   delhi   16000     teacher

In [24]:
# removing columns in datafarme

In [25]:
d2.drop("designation",axis=1)

     NAME  AGE    CITY  SALARY
0    Ram    34  bhopal    5000
1  chetan   21  indore   10000
2    hari   22   delhi   16000

In [26]:
d2

     NAME  AGE    CITY  SALARY designation
0    Ram    34  bhopal    5000      doctor
1  chetan   21  indore   10000         eng
2    hari   22   delhi   16000     teacher

In [29]:

d2

     NAME  AGE    CITY  SALARY
0    Ram    34  bhopal    5000
1  chetan   21  indore   10000
2    hari   22   delhi   16000

In [33]:
d2.drop("SALARY",axis=1,inplace=True)
d2

     NAME  AGE    CITY
0    Ram    34  bhopal
1  chetan   21  indore
2    hari   22   delhi

In [34]:
# again add the new column

In [36]:
d2["SALARY"] = [50000,100000,120000]
d2

     NAME  AGE    CITY  SALARY
0    Ram    34  bhopal   50000
1  chetan   21  indore  100000
2    hari   22   delhi  120000

In [37]:
# removing the row

In [39]:
d2.drop(2,axis=0,inplace=True)
d2

     NAME  AGE    CITY  SALARY
0    Ram    34  bhopal   50000
1  chetan   21  indore  100000

In [40]:
d2

     NAME  AGE    CITY  SALARY
0    Ram    34  bhopal   50000
1  chetan   21  indore  100000

In [41]:
data_list = [
    ["Ram ",34, "bhopal",5000],
    ["chetan",21 ,"indore",10000],
    ["hari",22,"delhi",16000]
]
d2= pd.DataFrame(data_list)
d2

        0   1       2      3
0    Ram   34  bhopal   5000
1  chetan  21  indore  10000
2    hari  22   delhi  16000

In [42]:
column = ["NAME","AGE","CITY","SALARY"]
d2=pd.DataFrame(data_list,columns=column)
d2

     NAME  AGE    CITY  SALARY
0    Ram    34  bhopal    5000
1  chetan   21  indore   10000
2    hari   22   delhi   16000

In [43]:
# selecting a row

In [46]:
d2.loc[0]

NAME        Ram
AGE           34
CITY      bhopal
SALARY      5000
Name: 0, dtype: object

In [47]:
d2.loc[[0,1]]

     NAME  AGE    CITY  SALARY
0    Ram    34  bhopal    5000
1  chetan   21  indore   10000

In [48]:
# SLECTING SUBSETS OF ROWS AND COLUMS 

d2.loc[[0,1]][["CITY","SALARY"]]

     CITY  SALARY
0  bhopal    5000
1  indore   10000

In [49]:
# SELECTS NAME AND AGE COLUMNS

In [51]:
d2.loc[[0,1,2]][["NAME","AGE"]]

     NAME  AGE
0    Ram    34
1  chetan   21
2    hari   22

In [52]:
# CONDITIONAL SELECTION

In [53]:
# i only want tpo see those people whose ag eis above 30.
d2[d2["AGE"]>30]

   NAME  AGE    CITY  SALARY
0  Ram    34  bhopal    5000

In [54]:
# i only want tpo see those people whose ag eis above 30 ,and city is paris
d2[(d2["AGE"]>30) & (d2["CITY"]=="bhopal")]

   NAME  AGE    CITY  SALARY
0  Ram    34  bhopal    5000