In [1]:
import numpy as np
import pandas as pd

In [2]:

data = {
    'Region': ['North', 'North', 'South', 'South'],
    'Product': ['Laptop', 'Phone', 'Laptop', 'Phone'],
    'Sales': [1000, 500, 800, 600]
}

df = pd.DataFrame(data)

print(df)

  Region Product  Sales
0  North  Laptop   1000
1  North   Phone    500
2  South  Laptop    800
3  South   Phone    600

In [5]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc="sum")

Product  Laptop  Phone
Region
North      1000    500
South       800    600

In [ ]:
# crosstab functiobn

In [6]:
pd.crosstab(df["Region"],df["Product"])

Product  Laptop  Phone
Region
North         1      1
South         1      1